import { AppData } from './types';

export const SEED_DATA: AppData = {
  users: [
    {
      id: 'u001',
      firstname: 'Admin',
      surname: 'System',
      nickname: 'Admin',
      email: 'admin@school.ac.th',
      role: 'admin',
      profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
      bio: 'System administrator',
      password: 'admin123',
      selectedClubs: {},
      clubHistory: [],
      treasureAnswers: {},
    },
    {
      id: 'u002',
      firstname: 'Siriporn',
      surname: 'Khamdi',
      nickname: 'Nong',
      email: 'siriporn@school.ac.th',
      role: 'student',
      profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nong',
      bio: 'Love coding and music 🎵',
      password: 'pass123',
      selectedClubs: {},
      clubHistory: [],
      treasureAnswers: {},
    },
    {
      id: 'u003',
      firstname: 'Tanapat',
      surname: 'Srisuk',
      nickname: 'Film',
      email: 'tanapat@school.ac.th',
      role: 'student',
      profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=film',
      bio: 'Basketball & Science enthusiast',
      password: 'pass123',
      selectedClubs: {},
      clubHistory: [],
      treasureAnswers: {},
    },
  ],
  clubs: [
    {
      id: 'c001',
      name: 'Robotics Club',
      description: 'Build and program robots, participate in competitions, and explore the intersection of engineering and computer science.',
      type: 'STEM',
      capacity: 20,
      members: [],
      imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&q=80',
    },
    {
      id: 'c002',
      name: 'Art & Design Club',
      description: 'Express creativity through painting, digital art, sculpture, and design thinking. Open to all skill levels.',
      type: 'Arts',
      capacity: 15,
      members: [],
      imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&q=80',
    },
    {
      id: 'c003',
      name: 'Music Ensemble',
      description: 'Play classical and modern music together. Instruments welcome, vocals too! Perform at school events.',
      type: 'Arts',
      capacity: 25,
      members: [],
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80',
    },
    {
      id: 'c004',
      name: 'Science Research',
      description: 'Conduct real research projects, attend seminars, and publish findings. Mentored by university professors.',
      type: 'STEM',
      capacity: 12,
      members: [],
      imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400&q=80',
    },
    {
      id: 'c005',
      name: 'Debate Society',
      description: 'Sharpen critical thinking and public speaking. Compete in national and international debate tournaments.',
      type: 'Academic',
      capacity: 18,
      members: [],
      imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=400&q=80',
    },
    {
      id: 'c006',
      name: 'Environmental Club',
      description: 'Lead sustainability initiatives, organize clean-up events, and raise awareness about environmental issues.',
      type: 'Community',
      capacity: 30,
      members: [],
      imageUrl: 'https://images.unsplash.com/photo-1542601906897-0d35d2f66e3f?w=400&q=80',
    },
  ],
  clubRounds: [
    {
      round: 1,
      openAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
      closeAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    {
      round: 2,
      openAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      closeAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
    {
      round: 3,
      openAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
      closeAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    },
    {
      round: 4,
      openAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
      closeAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
    },
  ],
  treasureAnswers: [
    { slot: 0, answer: 'purple' },
    { slot: 1, answer: 'robot' },
    { slot: 2, answer: 'science' },
    { slot: 3, answer: 'music' },
    { slot: 4, answer: 'debate' },
    { slot: 5, answer: 'green' },
    { slot: 6, answer: 'code' },
    { slot: 7, answer: 'art' },
    { slot: 8, answer: 'nature' },
    { slot: 9, answer: 'school' },
    { slot: 10, answer: 'club' },
    { slot: 11, answer: 'hunt' },
  ],
  activities: [
    {
      id: 'a001',
      date: '2025-05-10',
      time: '09:00',
      title: 'Opening Ceremony',
      location: 'Main Hall',
      description: 'Welcome all new club members with presentations and performances.',
      type: 'Ceremony',
    },
    {
      id: 'a002',
      date: '2025-05-15',
      time: '13:00',
      title: 'Robotics Workshop',
      location: 'Science Lab B',
      description: 'Intro to Arduino and sensor programming for Robotics Club.',
      type: 'Workshop',
    },
    {
      id: 'a003',
      date: '2025-05-20',
      time: '10:00',
      title: 'Art Exhibition',
      location: 'Gallery Room',
      description: 'Showcase student artwork from the Art & Design Club.',
      type: 'Exhibition',
    },
    {
      id: 'a004',
      date: '2025-05-25',
      time: '14:00',
      title: 'Debate Championship',
      location: 'Auditorium',
      description: 'Inter-school debate tournament — Round 1.',
      type: 'Competition',
    },
    {
      id: 'a005',
      date: '2025-06-01',
      time: '08:00',
      title: 'Treasure Hunt Event',
      location: 'School Campus',
      description: 'Campus-wide treasure hunt challenge for all students.',
      type: 'Event',
    },
    {
      id: 'a006',
      date: '2025-06-10',
      time: '15:00',
      title: 'Music Concert',
      location: 'Auditorium',
      description: 'Live performance by the Music Ensemble and guest artists.',
      type: 'Performance',
    },
  ],
  treasureCooldowns: {},
};
